version: '3.9'

services:
  database:
    image: 'postgres:latest'
    container_name: 'flashcards-backend-db'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: pass # The PostgreSQL password (useful to connect to the database)
