spring:
  liquibase:
    change-log: classpath:/db.changelogs/changelog-root.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: none
